name: triality-qutrit
channels: [conda-forge, pytorch]
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - pytorch
  - pytorch-cpu
  - botorch
  - gpytorch
  - pyyaml
  - jupyter
  - pip
  - pip:
      - seaborn
